project:
  type: website

execute:
  echo: true
  warning: false

website:
  title: "R Workshop for Methods Peer Group"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Slides  
        menu:
        - text: "Part 1"
          href: slides_01.qmd
        - text: "---"
        - text: "Part 2"
          href: slides_02.qmd
      - text: Scripts
        menu:
        - text: Examples
          href: "script_examples.R"
        - text: R Packages
          href: "script_package.R"

      - href: literatur.qmd
        text: References

format:
  html:
    theme: cosmo
    from: markdown+emoji
    css: styles.css
    toc: true



