project:
  type: website

execute:
  echo: true
  warning: false

website:
  title: "R Workshop für Peergroup Methoden"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Folien  
        menu:
        - text: "Programmieren"
          href: programming_01.qmd
        - text: "---"
        - text: "Reproduzierbarkeit"
          href: reproducible_01.qmd

      - href: literatur.qmd
        text: Literatur

format:
  html:
    theme: cosmo
    from: markdown+emoji
    css: styles.css
    toc: true



