project:
  type: website
  render:
      - "*.qmd"
      - "!quarto_example.qmd"

execute:
  echo: true
  warning: false

website:
  title: "R Workshop for Methods Peer Group"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Slides  
        menu:
        - text: "Part 1"
          href: slides_01.qmd
        - text: "---"
        - text: "Part 2"
          href: slides_02.qmd
      - text: Scripts
        menu:
        - text: Examples
          href: "/examples/script_examples.R"
        - text: Example Script package development
          href: "/examples/script_package.R"
        - text: Quarto Example
          href: "examples/quarto_example.qmd"

      - href: literatur.qmd
        text: References

format:
  html:
    theme: cosmo
    from: markdown+emoji
    css: styles.css
    toc: true



